In [1]:
import nltk
import pandas as pd
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import BernoulliNB
from sklearn.svm import SVC
from sklearn.linear_model import SGDClassifier
from sklearn.pipeline import Pipeline
from sklearn.cross_validation import KFold, cross_val_score
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import confusion_matrix, f1_score, precision_score, recall_score
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn import metrics 
import matplotlib.pyplot as plt
from sklearn.model_selection import learning_curve
from sklearn.model_selection import ShuffleSplit
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import permutation_test_score
import re
import random
from sklearn.linear_model import LogisticRegression

/Users/fatma/anaconda2/envs/py35/lib/python3.5/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [23]:
ready_cf_dataset_09_05_2018 = pd.read_csv("Data/ready_cf_dataset_09_05_2018.csv")

In [3]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to /Users/fatma/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [4]:
def clean_str(string):
    """
    Tokenization/string cleaning for all datasets except for SST.
    Original taken from https://github.com/yoonkim/CNN_sentence/blob/master/process_data.py
    """
    string = re.sub(r"[^A-Za-z0-9(),!?\'\`]", " ", string)
    string = re.sub(r"\'s", " ", string)
    string = re.sub(r"\'ve", " ", string)
    string = re.sub(r"n\'t", " ", string)
    string = re.sub(r"n\'s", " ", string)
    string = re.sub(r"\'re", " ", string)
    string = re.sub(r"\'d", " ", string)
    string = re.sub(r"\'ll", " ", string)
    string = re.sub(r",", " ", string)
    string = re.sub(r"!", " ", string)
    string = re.sub(r"\(", " ", string)
    string = re.sub(r"\)", " ", string)
    string = re.sub(r"\?", " ", string)
    string = re.sub(r"\s{2,}", " ", string)
    string = re.sub(r"\//?", " ", string)
    string = re.sub(r"\d+", " ", string)
    string = re.sub(r"\$", " ", string)
    string = re.sub(r"\#", " ", string)
    return string.strip().lower()

In [5]:
def remove_stop(str):
    stop = set(stopwords.words('english'))
    lst = str.split()
    lst = [i for i in lst if i not in stop]
    return ' '.join(lst)

def stem (str):
    lst = str.split()
    lst = [st.stem(x) for x in lst]
    return ' '.join(lst)

def remove_unwanted_words(str):
    unwanted_words = ["httpaddress", "usrid", "D", "dd", "rt", "amp", "am", "pm", '``',
                      "''", "", "//", "\\", "\\'s", "\\?", "\?","http","httpaddresshttpaddresst", "cohttpaddressek",
                      "taksim","gezi", "park", "direngeziparki", "occupygezi", "istanbul", "turkish","turkey",
                      "protest","direngezipark","direnankara","geziparki", "protesters", "protests", "sat", "sun", "mon,",
                     "tue", "wed", "thu", "fri", "jan", "feb", "mar", "apr", "may", "jun", "jul", "aug", "sep", "oct", "nov", "dec"]
    lst = str.split(" ")
    lst = [i for i in lst if i not in unwanted_words]
    return ' '.join(lst)

def toLower(str):
    lst = str.split()
    lst = [i.lower() for i in lst]
    return ' '.join(lst)

def word_len (str):
    lst = str.split()
    lst = [i for i in lst if len(i)>1 and len(i) <7]
    return ' '.join(lst)

def sent_len (str):
    lst = str.split()
    if len(lst)>=3:
        return ' '.join(lst)

In [6]:
def load_data_and_labels_shuffled(positive_data_file, negative_data_file):
    """
    Loads MR polarity african_data from files, splits the african_data into words and generates labels.
    Returns split sentences and labels.
    """
    # Load african_data from files
    positive_examples = list(open(positive_data_file, "r").readlines())
    positive_examples = [s.strip() for s in positive_examples]
    positive_examples = [remove_stop(item) for item in positive_examples]
    #print(positive_examples[0])
    positive_examples = [toLower(item) for item in positive_examples]
    #rint(positive_examples[0])
    positive_examples = [clean_str(sent) for sent in positive_examples]
    #rint(positive_examples[0])
    #positive_examples = [stem(item) for item in positive_examples]
    #rint(positive_examples[0])
    positive_examples = [remove_unwanted_words(item) for item in positive_examples]
    positive_examples = [word_len(item) for item in positive_examples]
    positive_examples = [sent_len(item) for item in positive_examples]
    positive_examples = list(filter(None, positive_examples))
    negative_examples = list(open(negative_data_file, "r").readlines())
    negative_examples = [s.strip() for s in negative_examples]
    negative_examples = [toLower(item) for item in negative_examples]
    #print(negative_examples[0])
    negative_examples = [remove_stop(item) for item in negative_examples]
    #print(negative_examples[0])
    negative_examples = [clean_str(sent) for sent in negative_examples]
    #print(negative_examples[0])
    #ngative_examples = [stem(sent) for sent in negative_examples]
    #pint(negative_examples[0])
    negative_examples = [remove_unwanted_words(item) for item in negative_examples]
    negative_examples = [word_len(item) for item in negative_examples]
    #print(negative_examples[0])
    negative_examples = [sent_len(item) for item in negative_examples]

    negative_examples = list(filter(None, negative_examples))

    # Split by words
    x_text = positive_examples + negative_examples
    # x_text = [clean_str(sent) for sent in x_text]
    # Generate labels
    positive_labels = [1 for _ in positive_examples]
    negative_labels = [0 for _ in negative_examples]
    y = np.concatenate([positive_labels, negative_labels], 0)
    return [x_text, y]

In [44]:
len(ready_cf_dataset_09_05_2018)

1735

In [36]:
len(ready_cf_dataset_09_05_2018[ready_cf_dataset_09_05_2018["violence"]==1])

205

In [37]:
len(ready_cf_dataset_09_05_2018[ready_cf_dataset_09_05_2018["violence"]==0])

1530

In [24]:
X_train, X_test, y_train, y_test = train_test_split(ready_cf_dataset_09_05_2018.proccd_text, 
                                                    ready_cf_dataset_09_05_2018.violence, 
                                                    test_size=0.3, random_state=0)

In [25]:
train_df = pd.concat([X_train,y_train],axis=1)
test_df = pd.concat([X_test,y_test],axis = 1)

In [45]:
len(train_df)

1214

In [38]:
len(train_df[train_df["violence"]==1])

151

In [40]:
len(train_df[train_df["violence"]==0])

1063

In [46]:
len(test_df)

521

In [42]:
len(test_df[test_df["violence"]==1])

54

In [43]:
len(test_df[test_df["violence"]==0])

467

In [26]:
pipeline_violence_Svc = Pipeline([
    ('vectorizer',  CountVectorizer(ngram_range=(1, 2),stop_words='english',  min_df=3)),
    ('tfidf_transformer',  TfidfTransformer()),
    ('classifier',  SVC(kernel='linear', gamma=2)) ])

    
scores = cross_val_score(pipeline_violence_Svc, train_df.proccd_text, train_df.violence, cv=5)

In [56]:
print('scores',scores)
print('scores mean',scores.mean())
print('scores std',scores.std() * 2)

('scores', array([ 0.86885246,  0.86831276,  0.89300412,  0.88429752,  0.88842975]))
('scores mean', 0.88057932083432999)
('scores std', 0.020353233995855032)


In [51]:
cv_predict = cross_val_predict(pipeline_violence_Svc, train_df.proccd_text, train_df.violence, cv=5)
cv_predict_scores = metrics.roc_auc_score(train_df.violence, cv_predict)

In [52]:
cv_predict_scores

0.59941250864415974

In [28]:
pipeline_violence_Svc.fit(train_df.proccd_text, train_df.violence)

Pipeline(steps=[('vectorizer', CountVectorizer(analyzer=u'word', binary=False, decode_error=u'strict',
        dtype=<type 'numpy.int64'>, encoding=u'utf-8', input=u'content',
        lowercase=True, max_df=1.0, max_features=None, min_df=3,
        ngram_range=(1, 2), preprocessor=None, stop_words='english',...,
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False))])

In [29]:
prediction = pipeline_violence_Svc.predict(test_df.proccd_text)

In [32]:
metrics.roc_auc_score(test_df.violence,prediction)

0.58402728210008714

In [33]:
metrics.confusion_matrix(test_df.violence,prediction)

array([[459,   8],
       [ 44,  10]])

# svm on the same DS used in dann_tf_code

In [7]:
text, y = load_data_and_labels_shuffled('Data/Turkish_tweets_CF_results_09_05_2018_prccd_pos.txt', 'Data/Turkish_tweets_CF_results_09_05_2018_prccd_neg.txt')

In [8]:
df = pd.DataFrame({'proccd_text': list(text),'violence': y})

In [9]:
len(df)

1333

In [10]:
len(df[df["violence"]==1])

180

In [11]:
len(df[df["violence"]==0])

1153

In [27]:
test_predict_auc_all =[]
for i in range(1,10):
    df_X_train, df_X_test, df_y_train, df_y_test = train_test_split(df.proccd_text, 
                                                    df.violence, 
                                                    test_size=0.5)
    df_train_df = pd.concat([df_X_train,df_y_train],axis=1)
    df_test_df = pd.concat([df_X_test,df_y_test],axis = 1)
    print('training set size', len(df_train_df))
    print('training pos', len(df_train_df[df_train_df["violence"]==1]))
    print('training neg', len(df_train_df[df_train_df["violence"]==0]))
    print('test set size', len(df_test_df))
    print('test pos', len(df_test_df[df_test_df["violence"]==1]))
    print('test neg', len(df_test_df[df_test_df["violence"]==0]))
    
    df_pipeline_violence_Svc = Pipeline([
    ('vectorizer',  CountVectorizer(ngram_range=(1, 2),stop_words='english',  min_df=3)),
    ('classifier',  SVC(kernel='linear', probability=True)) ])

    
    df_scores = cross_val_score(df_pipeline_violence_Svc, df_train_df.proccd_text, df_train_df.violence, cv=10)
    print('scores',df_scores)
    print('scores mean',df_scores.mean())
    print('scores std',df_scores.std() * 2)
    
    df_cv_predict = cross_val_predict(df_pipeline_violence_Svc, df_train_df.proccd_text, df_train_df.violence, cv=10)
    df_cv_predict_scores = metrics.roc_auc_score(df_train_df.violence, df_cv_predict)
    print('cv auc', df_cv_predict_scores)
    
    df_pipeline_violence_Svc_model = df_pipeline_violence_Svc.fit(df_train_df.proccd_text, df_train_df.violence)
    df_prediction = df_pipeline_violence_Svc_model.predict(df_test_df.proccd_text)
    df_predict_prob = df_pipeline_violence_Svc_model.predict_proba(df_test_df.proccd_text)
    test_predict_auc = metrics.roc_auc_score(df_test_df.violence,df_prediction)
    print('test set auc', test_predict_auc)
    test_predict_auc_all.append(test_predict_auc)
    print(metrics.confusion_matrix(df_test_df.violence,df_prediction))

training set size 666
training pos 87
training neg 579
test set size 667
test pos 93
test neg 574
scores [0.88059701 0.82089552 0.89552239 0.82089552 0.85074627 0.86567164
 0.8358209  0.89393939 0.89393939 0.84615385]
scores mean 0.8604181887763976
scores std 0.05635799021744995
cv auc 0.602257161574653
test set auc 0.6627608557191563
[[551  23]
 [ 59  34]]
training set size 666
training pos 86
training neg 580
test set size 667
test pos 94
test neg 573
scores [0.88059701 0.91044776 0.80597015 0.88059701 0.91044776 0.92537313
 0.92424242 0.86363636 0.86363636 0.93939394]
scores mean 0.8904341926729986
scores std 0.07569895867099173
cv auc 0.684522854851644
test set auc 0.6557962942334113
[[526  47]
 [ 57  37]]
training set size 666
training pos 88
training neg 578
test set size 667
test pos 92
test neg 575
scores [0.89552239 0.92537313 0.85074627 0.88059701 0.89552239 0.86567164
 0.86567164 0.8358209  0.84615385 0.89230769]
scores mean 0.8753386911595866
scores std 0.052302611769167
cv

In [28]:
np.mean(test_predict_auc_all)

0.6433478610021472

In [29]:
df_test_df['svm_prdiction'] = df_prediction

In [34]:
df_prediction[0]

0

In [35]:
df_predict_prob[:,0]

array([0.90611842, 0.91599844, 0.96453685, 0.94646044, 0.9392396 ,
       0.94552106, 0.87060375, 0.93272095, 0.91657136, 0.95292846,
       0.59919543, 0.6299857 , 0.95397339, 0.93272095, 0.95067852,
       0.24985528, 0.92045423, 0.8706347 , 0.98910086, 0.9470751 ,
       0.9580288 , 0.9003339 , 0.95396814, 0.87559225, 0.93818358,
       0.93780951, 0.93907114, 0.93891251, 0.9822848 , 0.93272095,
       0.7728008 , 0.8904012 , 0.94393188, 0.93272095, 0.81543005,
       0.96956701, 0.93272095, 0.91389529, 0.93648756, 0.93272095,
       0.93272095, 0.93272095, 0.77286331, 0.93272095, 0.7890198 ,
       0.63602316, 0.89462509, 0.93272095, 0.93206414, 0.96377094,
       0.92536193, 0.87765674, 0.93272095, 0.93272095, 0.8181539 ,
       0.8619701 , 0.93272095, 0.97089547, 0.53426665, 0.93272095,
       0.8181539 , 0.9830676 , 0.84760577, 0.9286054 , 0.93272095,
       0.85214177, 0.90327074, 0.9580288 , 0.9709391 , 0.93272095,
       0.96552478, 0.56308506, 0.87765674, 0.93272095, 0.77286

In [36]:
df_test_df['svm_0_probabilities(non_violence)'] = df_predict_prob[:,0]
df_test_df['svm_1_probabilities(violence)'] = df_predict_prob[:,1]

In [38]:
df_test_df.to_csv('Data/svm_predctions.csv')

In [16]:
len(df_train_df[df_train_df["violence"]==0])

798

In [17]:
len(df_test_df)

400

In [18]:

len(df_test_df[df_test_df["violence"]==1])


45

In [19]:

len(df_test_df[df_test_df["violence"]==0])

355

In [20]:
df_pipeline_violence_Svc = Pipeline([
    ('vectorizer',  CountVectorizer(ngram_range=(1, 2),stop_words='english',  min_df=3)),
    ('classifier',  SVC(kernel='linear', gamma=2)) ])

    
df_scores = cross_val_score(df_pipeline_violence_Svc, df_train_df.proccd_text, df_train_df.violence, cv=5)

In [21]:
print('scores',df_scores)
print('scores mean',df_scores.mean())
print('scores std',df_scores.std() * 2)

('scores', array([ 0.90374332,  0.86631016,  0.86096257,  0.8172043 ,  0.89247312]))
('scores mean', 0.8681386924271175)
('scores std', 0.060060009965560136)


In [22]:
df_cv_predict = cross_val_predict(df_pipeline_violence_Svc, df_train_df.proccd_text, df_train_df.violence, cv=5)
df_cv_predict_scores = metrics.roc_auc_score(df_train_df.violence, df_cv_predict)

In [23]:
df_cv_predict_scores

0.66752993595098864

In [24]:
df_pipeline_violence_Svc.fit(df_train_df.proccd_text, df_train_df.violence)

Pipeline(steps=[('vectorizer', CountVectorizer(analyzer=u'word', binary=False, decode_error=u'strict',
        dtype=<type 'numpy.int64'>, encoding=u'utf-8', input=u'content',
        lowercase=True, max_df=1.0, max_features=None, min_df=3,
        ngram_range=(1, 2), preprocessor=None, stop_words='english',...,
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False))])

In [25]:
df_prediction = df_pipeline_violence_Svc.predict(df_test_df.proccd_text)

In [26]:
metrics.roc_auc_score(df_test_df.violence,df_prediction)

0.6912363067292645

In [27]:
metrics.confusion_matrix(df_test_df.violence,df_prediction)

array([[333,  22],
       [ 25,  20]])

# Logistic regreswsion

In [28]:
lr_pipeline_violence_Svc = Pipeline([
    ('vectorizer',  CountVectorizer(ngram_range=(1, 2),stop_words='english',  min_df=3)),
    ('classifier',  LogisticRegression()) ])

    
lr_scores = cross_val_score(lr_pipeline_violence_Svc, df_train_df.proccd_text, df_train_df.violence, cv=5)

In [29]:
print('scores',lr_scores)
print('scores mean',lr_scores.mean())
print('scores std',lr_scores.std() * 2)

('scores', array([ 0.90374332,  0.87700535,  0.87700535,  0.86021505,  0.88172043]))
('scores mean', 0.87993789891323093)
('scores std', 0.027943737931744168)


In [30]:
lr_cv_predict = cross_val_predict(lr_pipeline_violence_Svc, df_train_df.proccd_text, df_train_df.violence, cv=5)
lr_cv_predict_scores = metrics.roc_auc_score(df_train_df.violence, lr_cv_predict)

In [31]:
lr_cv_predict_scores

0.65595934280144808

In [32]:
lr_pipeline_violence_Svc.fit(df_train_df.proccd_text, df_train_df.violence)

Pipeline(steps=[('vectorizer', CountVectorizer(analyzer=u'word', binary=False, decode_error=u'strict',
        dtype=<type 'numpy.int64'>, encoding=u'utf-8', input=u'content',
        lowercase=True, max_df=1.0, max_features=None, min_df=3,
        ngram_range=(1, 2), preprocessor=None, stop_words='english',...ty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False))])

In [33]:
lr_prediction = lr_pipeline_violence_Svc.predict(df_test_df.proccd_text)

In [34]:
metrics.roc_auc_score(df_test_df.violence,lr_prediction)

0.65805946791862291

In [35]:
metrics.confusion_matrix(df_test_df.violence,lr_prediction)

array([[341,  14],
       [ 29,  16]])